# Generated by Django 5.1.7 on 2025-05-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField(default="this is cool")),
                ("image", models.ImageField(upload_to="product/images")),
                ("price", models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
    ]
