# Generated by Django 5.1.7 on 2025-06-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity_avail",
            field=models.DecimalField(
                decimal_places=0, default=1, max_digits=1000000000
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity_cart",
            field=models.DecimalField(
                decimal_places=0, default=1, max_digits=1000000000
            ),
        ),
    ]
