# Generated by Django 5.1.7 on 2025-06-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_quantity_avail_product_quantity_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity_cart",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=1000000000
            ),
        ),
    ]
