# Generated by Django 5.1.7 on 2025-06-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_quantity_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity_cart",
            field=models.DecimalField(
                decimal_places=0, default=1, max_digits=1000000000
            ),
        ),
    ]
